on:
 push:
   branches:
     - master
   tags:
     - "*telephone directory*"
name: "Continuous Deployment"# Объявляем Jobs
jobs:
 build:
   name: "Build and deploy"
   runs-on: ubuntu-latest 

   env:
     DOCKER_IMAGE: Funlik/Lab_2_ns_Telephone-directory
     
   steps:
   - name: "Checkout"
     uses: actions/checkout@v1

